### PR TITLE
Dependencies update

### PR DESCRIPTION
**Pull request by jelmansouri-legion**
This one is a bit more complicated and needs a small refactor

### CODE REVIEW

**Comment by jelmansouri-legion** [comment]
@rainliu before I spend more time on this. ServerCertVerifier now needs to be created with the root certificates, but it seems that actually setting the ServerCertVerifier is not yet in place, does that make sense?

**Comment by data-retriever** [comment]
Do you need help here? The old p256 version is making the lib incompatible with libp2p-core

**Comment by rainliu** [comment]
> 

Yes, please.

**Comment by melekes** [comment]
> Do you need help here? The old p256 version is making the lib incompatible with libp2p-core

I'm having the same issue wrt https://github.com/libp2p/rust-libp2p/pull/2622

**Comment by melekes** [comment]
I believe this can be closed now since https://github.com/webrtc-rs/dtls/pull/14 was merged. @rainliu any plans of releasing a new version?

**Comment by k0nserv** [comment]
Closed in favour of #14

**Pull request closed without merging**
